### ISSUE TITLE
Links (@link) not resolving in IDEA.

### ISSUE THREAD

**Issue by norswap** [Abnaxos/pegdown-doclet#39]
Using the IDEA plugin, the links are detected but they are displayed in red in the help tooltip (the one you get by pressing Ctrl + Q) and clicking on them makes an error pop-up.

Here's the red link (the docstring was simply `{@link #main}`):

![](http://puu.sh/jQIJZ/548a14dc67.png)

The error message says "Windows cannot find PATH Make sure you typed the name correctly, and then try again.", where PATH is the following:

![](http://puu.sh/jQIAB/3a6caf59f4.png)

**Comment by aeracode** [comment]
:+1:

**Comment by Abnaxos** [comment]
I had this issue before, however, I noticed that the same thing happens with plain HTML JavaDocs, so I put this away as a general issue of IDEA's QuickDoc. Basically, all the doclet does is to convert the Markdown to HTML before feeding it to the default IDEA QuickDoc code, the `{@link …}` tag stays untouched. So, *theoretically*, this doesn't have anything to do with the plugin, which I could confirm back then.

However, to achieve that "process the markdown and feed the output into IDEA's default JavaDoc stuff" involved quite a lot of hacking, ignoring the API and coding against the implementation. It's even possible that I had to copy-paste some of IDEA's code there, I can't remember exactly. Therefore, it's theoretically possible that it's fixed in IDEA now, but the plugin misses the fix.

Is the link correctly clickable when the plugin is turned off?

**Comment by norswap** [comment]
The plain version worked when I posted the issue, and still does.

I just gave it another spin, this time on OSX, and the link still shows up in red with the pegdown-doclet plugin, but is not clickable. I will try it on Windows later and report.

It's crazy they that JetBrains doesn't support custom doclets in the editor.

**Comment by norswap** [comment]
Yup, same situation on Windows (link in red, not clickable).

**Comment by HaasJona** [comment]
Same behaviour on Linux using Idea 2016.1 RC1, disabling the plug-in fixes the issue, so it's not an IDEA bug.

**Comment by Abnaxos** [comment]
Fixed in 1.3-0 (ce2bf5b).
